# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-19 18:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IntSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255)),
                ('value', models.IntegerField(default=0)),
                ('date_modified', models.DateTimeField(verbose_name='date modified')),
            ],
        ),
    ]
